:preinstall_operators: %preinstall_operators%

== Welcome to the Citrix VDI on OpenShift Virtualization Demo
OpenShift Virtualization enables you to bring virtual machines onto a modern, Kubernetes-based infrastructure. Essentially it brings virtualized applications and services to a single platform, Red Hat OpenShift. It enables the development and delivery of new applications as well as the modernization of existing ones and can create applications that consist of virtual machines, containers, and serverless - all managed together using Kubernetes-native tools and paradigms.

The *Citrix VDI on OpenShift Virtualization Demo* is organized in the following sections:

* *Review environment*: This section reviews the *OpenShift* installation to be used for each of the following labs.
* *Citrix Virtual Apps and Desktops*: Configure to deliver *Applications* and *Desktops* using _HTML5_ and _Citrix Workspace Application_.

== What is OpenShift Virtualization?

* OpenShift Virtualization is a feature of Red Hat OpenShift; it is not an add-on or a separate product and is included with all entitlements.
* All current and future subscribers receive OpenShift Virtualization as part of their OpenShift subscription. It has been generally available since OpenShift 4.5.
* OpenShift Virtualization is based on the “container-native virtualization” technology being developed upstream under the KubeVirt project, a sandbox project in the Cloud Native Computing Foundation (CNCF). 
* It leverages the Red Hat Enterprise Linux KVM hypervisor, which is a mature and highly performant open-source hypervisor used by many organizations and cloud service providers globally and which has been under development for over 15 years. 
* OpenShift Virtualization leverages the RHEL KVM hypervisor and allows the VM to be managed by Kubernetes and KubeVirt. An OpenShift Virtualization VM uses Kubernetes scheduling, network, and storage infrastructure.
* OpenShift Virtualization includes entitlements for **unlimited virtual RHEL guests**. Guest licensing for other supported operating systems will need to be purchased separately.
* OpenShift Virtualization is SVVP certified with Microsoft for Windows guest support per the same rules that apply to Red Hat’s other KVM virtualization offerings.
* OpenShift Virtualization is only supported on bare metal physical servers, typically on-premises or dedicated hosting. Support for other topologies (OpenShift on virtualized infrastructure like RHV or vSphere, OpenShift on public cloud) is not supported at this time.

OpenShift Virtualization allows OpenShift to deploy, manage, and connect virtual machines to an OpenShift cluster. This includes the ability to connect to and manage those VMs using Kubernetes-native methods and take advantage of OpenShift features like Pipelines, GitOps, Service Mesh, and more.

== What is Citrix Virtual Apps and Desktops

*Citrix Virtual Apps and Desktops* are virtualization solutions that give IT control of virtual machines, applications, licensing, and security while providing anywhere access for any device.

*Citrix Virtual Apps and Desktops* allow:

* End users to run applications and desktops independently of the device’s operating system and interface.
* Administrators to manage the network and control access from selected devices or from all devices.
* Administrators to manage an entire network from a single data center.

== Next steps

If you would like to learn more about OpenShift Virtualization, please visit the https://www.redhat.com/en/technologies/cloud-computing/openshift/virtualization[landing page], review the https://docs.openshift.com/container-platform/latest/virt/about-virt.html[documentation], or view some of our demo videos on https://www.youtube.com/playlist?list=PLaR6Rq6Z4IqeQeTosfoFzTyE_QmWZW6n_[YouTube].